options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud auth configure-docker europe-west2-docker.pkg.dev'

  - name: 'gcr.io/cloud-builders/helm'
    args: ['repo', 'add', 'helm-artifact-repo', 'oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo']

  - name: 'gcr.io/cloud-builders/helm'
    args: ['package', '.']

  - name: 'gcr.io/cloud-builders/helm'
    args: ['push', 'service-with-auth-0.1.0.tgz', 'oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo:v1.0.0']