options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud components install docker-credential-gcr
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        gcloud auth print-access-token > /workspace/oauth-token
        ls /workspace/
        cat /workspace/oauth-token

  # - name: 'alpine/helm'
  #   args: ['repo', 'add', 'helm-artifact-repo', 'oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo']
  - name: 'alpine/helm'
    args: ["echo", "'hello'"]

  - name: 'alpine/helm'
    args: ['package', '.']

  - name: 'alpine/helm'
    args: ['push', '/workspace/service-with-auth-0.1.0.tgz', 'oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo']