apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: {{ .Values.service.name }}
  namespace: "{{ .Values.namespace }}-{{ .Values.rid }}"
spec:
  type: {{ .Values.service.type }}
  selector:
      app: nginx
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}