apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.virtualservice.name }}-{{ .Values.rid }}"
  namespace: {{ .Values.virtualservice.namespace }}
spec:
  hosts:
  - {{ .Values.virtualservice.host }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/{{ .Values.rid }}"
    rewrite:
      uri: /
    route:
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.namespace }}-{{ .Values.rid }}.svc.cluster.local"
        port:
          number: {{ .Values.service.port }}