apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Values.virtualservice.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.namespace }}.svc.cluster.local"
        port:
          number: {{ .Values.service.port }}